language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
notifications:
  email: false
script:
  - npm run syntax
  - npm test
after_script:
  - npm run coveralls
env:
  global:
    - secure: "a1l3M9IeUL7J28kW+reXHCNhOmOMC2HKaK7aO9qnqA86D0B7G0cZwISvlwooAoTr8JoAZeseFEJhfl7CfuFJlCPiojVdKedSr73Kc3XwDP+8Al4scdzNrIwivFH8RyVNroeDvVIL0TXEj/Q0y1eVtcNiI00NrzS+ZW6Wtlb6RPE="
    - secure: "bnrqsbVQijbqpJxxvjW0a1vMfYX+yUoKiM+52hN2QqZntv53Oo+uYq/0L9pqJBAEHu7HHmlUB1PEp9PuPW57lNKH8FFeE8dyy5VKtHcfAk6oSyzX43ZFTSKUK0zUylUw6F6cLLhutzYeNn/gBd+BB0c/eXiIcySSMMzwPsiWx+s="
    - secure: "BcUG1FAtLHZpE0oDcD2yVa1cja+hqZtZ/wAivbTh0tnjo+Kv+qnlsewqJgKmPqW7nmTT5Yh98Jy/7kGeqasuFu3crwG+bwfafhhESPPrZmICO5FmFfWJyOEF8Y+Ep78hVS9VQoI+sU1PcUyPXlg66Agngu6brk6l/9V7ZjqSThU="
    - secure: "ZwPNt7OVcoWWeQgA1LaGKZ0H6MIb5mDBOcxA8VtBrlp7AowmfkQTEAT3p95grWTpj/NJ1Jt9nz5HJWIBIFe7K6dJRqPHKcUbsY+2j/p3FhVvCYMKzK3qkD/YoApE1DQcJNmb0rNCuwA3KiNce8gJ9hw0KvRnonOd5I9TooVG4yE="
    - secure: "ZriQzOfKgRw1PEZKbnylO3/GsTuuuqaJHsLitjN3UQDJ2JlzZMfSr0v3bkpb4Ih+itwFEQi/o9qKzC8xbzQH/vncxX+kln9yrDtRuuqcFatRV5pgezDZK/X0misfP9CnljmXPPdian/0xaXnoHl2DIQ3m/5BpInFgEHRLIY5JVA="
